[package]
name = "cuttlefish-sdk"
description = "Guest-side library for writing cuttlefish proc-blocks"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
cuttlefish-abi = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
